### ISSUE TITLE
Slash commands Arguments

### ISSUE THREAD

**Issue by sluhtie** [DiSkyOrg/DiSky#119]
Hello, I'd like to request a previous Feature from leagacy Versions

In this snippet you could create slash commands directly using arguments in it and it would be registered by Disky automatically
https://discord.com/channels/818182471140114432/818225595284455464/889098501567414295

It basically allowes you to define what arguments the command shuld have using ` [<type={"Arg","Description"}>]` as pattern.
I believe this would be a very cool Feature and would make creating slash commands easier.

**Comment by SkyCraft78** [comment]
Hey there!
I'm sorry, but this is not possible anymore, or at least with the amount of customization options can have nowadays.
An advanced version of this system, including almost all possibilities such as auto-complete, parsing, pre-defined options, and more, would be a pain to create and maintain.
In addition, keep in mind this sort of system (command/section node system) are a bit heavy to parse and manage for the developers, as well as for the scripter since it does not tell where an error occurred!
Have a nice afternoon :)
