### ISSUE TITLE
Member boost event

### ISSUE THREAD

**Issue by Mav124004** [DiSkyOrg/DiSky#184]
Member boost event is not working properly is very rare to be work properly 1/10 times

**Comment by ItsTheSky** [comment]
Do you have the `guild members` intent enabled? And what about your caching filter? 
From JDA's Docs:
> This event requires the GUILD_MEMBERS intent to be enabled.
Additionally, this event requires the MemberCachePolicy to cache the updated members. Discord does not specifically tell us about the updates, but merely tells us the member was updated and gives us the updated member object. In order to fire a specific event like this we need to have the old member cached to compare against.

**Comment by Mav124004** [comment]
![image](https://github.com/DiSkyOrg/DiSky/assets/113462926/bbe0aa7f-d4e8-4200-801f-ccf4a5ed3d89)
![image](https://github.com/DiSkyOrg/DiSky/assets/113462926/86db93c0-7bca-4a9b-a8c1-e0f66a92aa9d)
![image](https://github.com/DiSkyOrg/DiSky/assets/113462926/104d029c-d92f-4a1d-8291-d8c5cf92e42e)
![image](https://github.com/DiSkyOrg/DiSky/assets/113462926/89946c19-97af-4a21-9292-a9e2c4604ff0)
![image](https://github.com/DiSkyOrg/DiSky/assets/113462926/9cc585ec-2641-4c62-a1f5-956d4165716d)

**Comment by ItsTheSky** [comment]
I added a way to get the user/member who boosted, but I'm not sure where the event not being fired comes from, as you seem to have enabled both Guild Members' intent & have the cache policy set to all.

**Comment by ItsTheSky** [comment]
Will be "changed" according to the new docs: https://disky.me/docs/docs/events/#on-member-boost-time-change-event
This will start from v4.15.2
