### ISSUE TITLE
User is able to select a role via a role menu even if they have a role that *should* prevent them from doing so

### ISSUE THREAD

**Issue by Juliaxe** [DiSkyOrg/DiSky#26]
How to reproduce:

- Make a dropdown menu
- Add a few role selections to it
- Make it so that the user can only select one option
- After selecting a role via this dropdown, wait 2 minutes for good measure
- Try to select a different role from the dropdown, it will allow you to

```vb
options:
	role female: 969280100229087272
	role male: 969280117522198619
	role nonbinary: 969280144172806195
	role genderfluid: 969280148367106069
```

```vb
on dropdown click:
	set {_id} to event-string
	if {_id} is "rolemenu_gender":
		if event-member has discord role with id "{@role female}" or "{@role male}" or "{@role nonbinary}" or "{@role genderfluid}":
			reply with hidden "❌ If you'd like to change your gender role, please contact support."
		else:
			if selected value is "female":
				add role with id "{@role female}" to event-member
				reply with hidden "✅ You selected Female."
			if selected value is "male":
				add role with id "{@role male}" to event-member
				reply with hidden "✅ You selected Male."
			if selected value is "nonbinary":
				add role with id "{@role nonbinary}" to event-member
				reply with hidden "✅ You selected Nonbinary."
			if selected value is "genderfluid":
				add role with id "{@role genderfluid}" to event-member
				reply with hidden "✅ You selected Genderfluid."
```

**Comment by Juliaxe** [comment]
Update: This issue also persists if you replace `if event-member has discord role with id "{@role female}" or "{@role male}" or "{@role nonbinary}" or "{@role genderfluid}":` with `if roles of event-member contains role with id "{@role female}" or "{@role male}" or "{@role nonbinary}" or "{@role genderfluid}":`.

**Comment by wallace4BR** [comment]
The issue is caused by how caching works, try using retrieve member effect instead of event-member

**Comment by SkyCraft78** [comment]
Because of how Skript works with list, you cannot pass multiple string as role, it's confusing I know so let me explain:

Basically, you're checking here :

- If the event-member has the role with id {@role female}
- Then if the event-member has a **string**, here `{@role male}`

Skript *could* pass the first condition (only if the whole statement was parsed successfully), but members cannot appropriate String, so Skript will return false for the other one. 

In order to make what you want, I highly recommend you to use the role's ID as the choice's ID, so that you avoid chained conditions and adding a new role will be done easier than before.
